//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationRole
    {
        public string AppRole_ID { get; set; }
        public string AppMenu_ID { get; set; }
        public string RolePer_ID { get; set; }
        public string AppRole_Name { get; set; }
        public string AppRole_Des { get; set; }
    
        public virtual ApplicationMenu ApplicationMenu { get; set; }
        public virtual RolePermission RolePermission { get; set; }
    }
}
