//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Authentication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public string UserRole_ID { get; set; }
        public string Role_ID { get; set; }
        public string UserAuthen_ID { get; set; }
        public string UserRole_Name { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual UserAuthentication UserAuthentication { get; set; }
    }
}
